name: Deploy Project to Server

permissions:
    contents: read

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    deploy:
        runs-on: [self-hosted]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
                echo "ALLOW_INSERT=false" >> .env
                echo "MONGODB_URI=mongodb://root:password@mongo:27018/?authSource=admin" >> .env

            
            - name: Update fireaid_web Dependancies
              run: |
                cd fireaid_web
                docker build -t fireaid_web_base:latest -f docker/Dockerfile-Base .

            - name: Build and Start Docker Containers
              run: |
                docker compose down
                docker compose build
                docker compose up -d 

            - name: Populate MongoDB with terms.csv
              run: |
                mongosh --port 27018 -u root -p password \
                  --eval "use fireaid" \
                  --eval "db.terms.deleteMany({})"
                query=""
                while read line;
                do
                    IFS=',' read -r term def <<< $line
                    query+="{term: \"$term\", def: $def},"
                done < ./scripts/term_scraper/terms.csv

                mongosh --port 27018 -u root -p password \
                  --eval "use fireaid" \
                  --eval "db.terms.insertMany([$query])"

